/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Fix export button and save": "修复导出按钮和保存",
    "ENABLED": "启用",
    "Export to file": "导出为文件",
    "Import clipboard": "从剪贴板导入",
    "Import file": "从文件导入",
    "DISABLED": "禁用",
    "Experience": "经验值",
    "| Day:": "| 天数:",
    "Req:": "需要:",
    "💰 Sell": "💰 出售",
    "exp": "经验值",
    "Additional Plot": "额加地块",
    "Almanac": "年历",
    "Auto Harvester": "自动收割机",
    "Auto-harvests when ready": "准备好后自动收割",
    "Auto-sells every 30 days": "每30天自动出售一次",
    "Better Seeds": "更好的种子",
    "Canning": "罐装",
    "Clear": "清除",
    "days to grow)": "天成熟)",
    "Doubles the effect of Better Seeds": "更好的种子的效果加倍",
    "Fertilizer": "肥料",
    "Greenhouse": "温室",
    "Growing": "生长中",
    "Growing Experience:": "成长经验：",
    "Growing...": "生长中...",
    "Heirloom Seeds": "传家宝种子",
    "Irrigation": "灌溉",
    "Knowledge:": "知识:",
    "Merchant": "商人",
    "Money: $": "金钱：$",
    "No sellable veggies": "没有可出售的蔬菜",
    "Plots:": "地块:",
    "Radish": "萝卜",
    "Snow": "下雪",
    "Stash:": "储藏：",
    "Upgrades": "升级",
    "Winter": "冬季",
    "Winter immunity": "冬季免疫",
    "Year:": "年份：",
    "Harvest": "收获",
    "Rain": "下雨",
    "Storm": "风暴",
    "Summer": "夏季",
    "Drought": "干旱",
    "Heatwave": "热浪",
    "Auto-Purchase:": "自动购买:",
    "days": "天",
    "🚫 Hold": "🚫 保留",
    "🚫 HOLD": "🚫 保留",
    "Sell All": "全部出售",
    "Fall": "秋季",
    "Buy Larger Farm:": "购买大农场:",
    "Kn/harvest": "Kn/收获",
    "Harvester Speed": "收获速度",
    "Knowledge+:": "知识+:",
    "Lettuce": "生菜",
    "Max Level": "满级",
    "Money/Knowledge kept:": "金钱/知识保存：",
    "Need Larger Farm": "需要大农场",
    "New max plots:": "新地块上限:",
    "Owned": "已拥有",
    "Spring": "春季",
    "(capped at 2x current)": "(上限为 2x 当前)",
    "Active Processes (": "活动进程 (",
    "All Recipes": "全部配方",
    "Batch Canning": "批量装罐",
    "MAX LEVEL": "满级",
    "By Difficulty": "按难度",
    "By Name": "按名称",
    "By Profit": "按利润",
    "By Time": "按时间",
    "Can Make": "可制作",
    "Canned Radish": "萝卜罐头",
    "Canner": "罐头机",
    "Canning Recipes": "罐头配方",
    "Complex": "复杂",
    "Family Recipe": "家传配方",
    "Gourmet": "美食家",
    "Heirloom Touch": "传家宝之触",
    "Quick Hands": "灵巧的手",
    "No active canning processes": "没有正在进行的罐装进程",
    "recipes unlocked": "配方已解锁",
    "Select a recipe above to start canning!": "选择上面的配方开始罐装吧！",
    "Simple": "简单",
    "Start Canning": "开始罐装",
    "Merchant: Next sale in": "商人：下次出售时间",
    "| Experience:": "| 经验值:",
    "Missing Ingredients": "缺少原料",
    "| Next Recipe at": "| 下一个配方",
    "Items Canned:": "罐装物品：",
    "Collect $": "收集 $",
    "Made": "制作",
    "times": "次",
    "s (": " (",
    "of": "/",
    "(Auto: +": "(自动: +",
    "(base:": "(基础:",
    "(base: $": "(基础: $",
    "(Have:": "(拥有:",
    "Better Seeds: +": "更好的种子: +",
    "Canned Lettuce": "生菜罐头",
    "Canning Experience:": "罐装经验：",
    "Cannot Start": "无法开始",
    "Ingredients Required:": "所需材料：",
    "Knowledge Reward:": "知识奖励:",
    "Preserved lettuce hearts in brine.": "用盐水腌制的莴苣心。",
    "Profit:": "利润:",
    "Processing Time:": "处理时间:",
    "Raw Value:": "原始价值:",
    "Sale Price:": "出售价格:",
    "Simple preserved radish. A great way to get started with canning.": "简单的腌萝卜。这是开始做罐头的好方法。",
    "Green Beans": "青豆",
    "Zucchini": "西葫芦",
    "Cucumbers": "黄瓜",
    "Tomatoes": "西红柿",
    "Carrots": "胡萝卜",
    "Peppers": "辣椒",
    "Canned Green Beans": "青豆罐头",
    "🔊 ON": "🔊 打开",
    "🔊 OFF": "🔊 关闭",
    "Close": "关闭",
    "Import Save": "导入存档",
    "Export Save": "导出存档",
    "Game Actions": "游戏操作",
    "Reset Game": "重置游戏",
    "Save Management": "存档管理",
    "Sound Effects:": "音效:",
    "Sound Settings": "声音设置",
    "This will permanently delete all progress!": "这将永久删除所有进度！",
    "The Canning System unlocks at 5,000 experience and allows you to process vegetables into preserved recipes for profit and rewards. Canning provides both money and valuable knowledge/experience bonuses.": "罐装系统在5000经验时解锁，允许您将蔬菜加工成保存的配方以获得利润和奖励。罐装提供金钱和有价值的知识/经验奖励。",
    "-30% growth penalty in Summer, +20% bonus to summer vegetables in spring and fall, +20% bonus to all vegetables in winter": "夏季-30%生长惩罚，春季和秋季夏季蔬菜+20%加成，冬季所有蔬菜+20%加成",
    "-50% growth penalty unless you have Irrigation, +1 Kn per day": "-50%成长惩罚，除非你有灌溉，每天+1知识",
    ". Each season lasts ~90 days and affects how your vegetables grow.": "． 每个季节持续约90天，影响蔬菜的生长。",
    "+0.5 Knowledge per vegetable harvested": "每收获一种蔬菜增加0.5点知识",
    "+1 Knowledge per vegetable harvested": "每收获一种蔬菜+1知识",
    "+1.25 Knowledge per harvest per farm tier": "每层农场每次收获增加1.25知识",
    "+10% growth boost for all vegetables": "所有蔬菜+10%生长提升",
    "+10% to ALL knowledge gains per level": "每升一级增加10%的知识增益",
    "+20% growth boost for all vegetables": "所有蔬菜+20%生长提升",
    "+5% harvester speed per level": "每升一级增加5%的收割机速度",
    "+5% multiplicative growth rate per level": "每级+5%的乘法增长率",
    "~97-99 depending on vegetable": "~97-99取决于蔬菜",
    "⚙️ Canning Upgrades:": "⚙️ 罐装升级：",
    "⚠️ IMPORTANT:": "⚠️ 重要:",
    "⚡ Harvester Speed": "⚡ 收割机速度",
    "🌟 Better Seeds (Knowledge Upgrade)": "🌟 更好的种子（知识升级）",
    "🌟 Heirloom Seeds": "🌟 传家宝种子",
    "🌦️ Weather System": "🌦️ 天气系统",
    "🎓 Experience System": "🎓 经验系统",
    "🎮 Button States & Visual Guide:": "🎮 按钮状态和视觉指南：",
    "🎯 How Auto-Purchasers Work:": "🎯 如何自动购买工作：",
    "🎯 How Canning Works:": "🎯 罐头如何工作：",
    "🎯 Purchase Priority System:": "🎯 优先采购制度：",
    "🏗️ Global Farm Upgrades": "️全球农场升级",
    "🏠 Greenhouse": "🏠 温室",
    "🏡 Plot System": "🏡 地块系统",
    "🏪 Merchant (Auto-Sell)": "🏪 商人（自动出售）",
    "💧 Irrigation System": "💧 灌溉系统",
    "📋 Recipe Information:": "📋 配方信息：",
    "📚 Farmer's Almanac (Knowledge Multiplier)": "📚 农民年鉴（知识乘数）",
    "📦 Additional Plots": "📦 附加地块",
    "🔧 Mechanic": "🔧 机械师",
    "🗺️ Surveyor": "🗺️ 测量员",
    "🤖 Auto Harvester": "🤖 自动收割机",
    "🤖 Auto-Canning System:": "🤖 自动罐装系统：",
    "🤖 Auto-Purchaser System": "🤖 自动购货系统",
    "🤝 Assistant": "🤝 助手",
    "🧑‍🌾 Cultivator": "🧑‍🌾 耕耘机",
    "🧠 Knowledge Currency": "🧠 知识货币",
    "🧪 Fertilizer (Growth Speed)": "🧪 肥料（生长速度）",
    "🚜 Farm Expansion (Prestige)": "🚜 农场扩展（声望）",
    "$1,000 + 100 Knowledge (one-time purchase, per farm)": "$1,000 + 100知识（一次性购买，每个农场）",
    "$10 → $17 → $25 → $34 → $44...": "$10→$17→$25→$34→$44……",
    "$2,500 + 200 Knowledge per highest vegetable unlocked": "每解锁一种最高的蔬菜2500 + 200知识",
    "$20 for Radish, scales by 1.4× per vegetable": "萝卜$20，每个蔬菜1.4倍",
    "$25 for Radish, scales by 1.5× per vegetable": "萝卜$25，每个蔬菜1.5倍",
    "$5 for Radish, scales by 1.4× per vegetable": "萝卜$5，每个蔬菜1.4倍",
    "$500 + 50 Knowledge (one-time purchase, per farm)": "$500 + 50知识（一次性购买，每个农场）",
    "$500 × 1.85^(farm tier) (exponential scaling)": "$500 × 1.85^（农场层级）（指数级扩展）",
    "$8 for Radish, scales by 1.5× per vegetable": "萝卜$8，每个蔬菜1.5倍",
    "0 exp (starting vegetable)": "0经验（初始蔬菜）",
    "1% chance all year": "全年1%的几率",
    "10 experience per ingredient (reduced for auto-canning)": "每种原料10点经验（自动罐装会减少）",
    "100% growth penalty (plants stop growing) unless you have a Greenhouse": "100%的生长惩罚（植物停止生长）除非你有一个温室",
    "2 knowledge per ingredient (reduced for auto-canning)": "每种原料2个知识（自动罐装减少）",
    "25% of current knowledge (1/3 retention)": "现有知识的25%（保留1/3）",
    "4 total plots across ALL vegetables": "所有蔬菜共4块地",
    "5 Knowledge for Radish, scales by 1.4× per vegetable": "5萝卜知识，每种菜1.4倍",
    "50 Knowledge + $500 (protects against Drought)": "50知识+ 500元（抗旱）",
    "50 seconds between harvest attempts": "每次收割间隔50秒",
    "90% growth penalty (only 10% normal speed) unless you own a Greenhouse": "90%的生长惩罚（只有10%的正常速度），除非你有一个温室",
    "Active Management:": "活动管理:",
    "Add Cultivator when you have steady knowledge income": "当你有稳定的知识收入时，添加耕耘者",
    "Add Mechanic after buying Auto Harvester for full automation": "购买全自动矿车后增加机械师",
    "Additional Plots:": "额外的地块:",
    "All active auto-purchasers attempt purchases simultaneously every 7 days": "所有活跃的自动购买者每7天尝试一次同时购买",
    "All auto-purchasers share a unified 7-day cycle timer": "所有自动购买者共享一个统一的7天周期计时器",
    "All growing vegetables and stashes cleared": "所有正在种植的蔬菜和储藏都清理干净了",
    "All Upgrades:": "所有的升级:",
    "All vegetables get +10% growth during their preferred seasons": "所有蔬菜在它们喜欢的季节都能得到+10%的增长",
    "Allows multiple simultaneous canning processes": "允许多个同时罐装过程",
    "Assistant → Cultivator → Surveyor → Mechanic": "助理→耕耘者→测量员→机械师",
    "Auto harvest gives +0.5 Knowledge vs +1 for manual": "自动收获给予+0.5知识vs +1手动收获",
    "Auto harvest gives 50% of the experience compared to manual harvest": "自动收获的经验值是手动收获的50%",
    "Auto Harvest:": "自动收获:",
    "Auto-canning gives 1/10th the knowledge and experience of manual canning": "自动罐装提供了1/10的知识和经验的手动罐装",
    "Auto-Purchaser Order:": "自动购买顺序:",
    "Auto-Purchaser Strategy:": "自动购买策略：",
    "Auto-Purchasers": "自动购买",
    "Auto-Purchasers automatically buy upgrades for you every 7 days when active and affordable. Each vegetable has its own set of auto-purchasers that operate independently.": "自动购买者每7天自动为您购买升级，当活跃和负担得起。每种蔬菜都有自己的一套独立运作的自动购买者。",
    "Automatic Reset:": "自动复位:",
    "Automatically expands production capacity": "自动扩大生产能力",
    "Automatically harvests when vegetables reach 100% growth": "当蔬菜达到100%生长时自动收获",
    "Automatically improves auto-harvester efficiency": "自动提高自动收割机效率",
    "Automatically increases sale prices for better profits": "自动提高销售价格以获得更好的利润",
    "Automatically selects and starts recipes every 10 seconds": "自动选择和开始每10秒的配方",
    "Automatically sells vegetables from stash every day": "每天从储藏中自动出售蔬菜",
    "Automatically starts recipes every 10 seconds": "每10秒自动启动配方",
    "Back to 0 (must re-unlock vegetables)": "回到0（必须重新解锁蔬菜）",
    "Balance Manual vs Auto:": "手动与自动平衡：",
    "Base Cost:": "基本费用:",
    "Base Timer:": "基本定时器:",
    "Batch Canning:": "批量罐装：",
    "Batch Processing:": "批量处理：",
    "Begin with single-ingredient recipes to learn the system": "从单一原料配方开始学习这个系统",
    "Benefit:": "好处:",
    "Better Seeds Level 3 = 1.95× without vs 3.375× with Heirloom": "更好的种子等级3 = 1.95×无传家宝vs 3.375×传家宝",
    "Better Seeds Timing:": "更好的播种时机：",
    "Better Seeds:": "更好的种子:",
    "Broccoli:": "西兰花:",
    "Broccoli": "西兰花",
    "%/day": "%/天",
    "each": "每个",
    "per cycle": "每个周期",
    "* Growth calculations are estimates based on current conditions and assume optimal growing conditions": "*增长计算是基于当前条件的估计，并假设最佳增长条件",
    "💰 Auto-sell": "💰 自动出售",
    "🚫 Stockpile": "🚫 库存",
    "Advanced Stash Details": "高级储藏详情",
    "Current Count & Value": "当前数量&价值",
    "days per cycle": "天每循环",
    "days/cycle": "天/周期",
    "Est. Annual Revenue": "预计年收入",
    "Est. Yearly Production": "预计年产量",
    "Growth Rate": "生长速率",
    "Sell Status (Click to Toggle)": "出售状态（点击切换）",
    "Total Stash:": "总储藏：",
    "total value": "总价值",
    "Total Value:": "总价值：",
    "Vegetable": "蔬菜",
    "Winter:": "冬天:",
    "Onions": "洋葱",
    "Uses Knowledge (Kn)": "使用知识 (Kn)",
    "Buy a new farm when you have excess money, experience and knowledge": "当你有多余的钱、经验和知识时，买一个新的农场",
    "Buy Assistant first for consistent fertilizer upgrades": "首先购买助手以获得持续的肥料升级",
    "Buy more plots for a lower tier vegetable is often more beneficial than waiting for higher tier vegetables": "购买更多的土地来种植较低层次的蔬菜通常比等待更高层次的蔬菜更有益",
    "Buy more plots per vegetable (costs money)": "每种菜买更多块地（需要钱）",
    "Buy Quick Hands first, then Family Recipe for better profits": "先买快手，再买家庭配方，这样利润会更好",
    "Calculation:": "计算:",
    "Can be turned on/off at any time after purchase": "是否可以在购买后随时开启/关闭",
    "Canner (Auto-Canning):": "罐头（自动装罐）：",
    "Canning Strategy:": "罐头的策略:",
    "Canning System": "灌装系统",
    "Carrots:": "胡萝卜:",
    "Clear:": "明确:",
    "Click any recipe for detailed breakdown and ingredient requirements": "点击任何配方查看详细的分解和配料要求",
    "Complete immunity to Drought weather penalty": "对干旱天气惩罚完全免疫",
    "Complete immunity to Winter and Snow penalties": "完全免疫冬天和雪的惩罚",
    "Condition:": "条件:",
    "Continuously improves growth speed without manual clicking": "无需手动点击即可持续提高生长速度",
    "Convenience:": "方便:",
    "Cost = previous cost × 1.15 + $5": "成本=之前的成本× 1.15 + $5",
    "Cost increases by 1.25× per level": "每升一级成本增加1.25倍",
    "Cost increases by 1.5× per level": "每升一级成本增加1.5倍",
    "Cost scales with highest unlocked veggie ever ($2,500 + 200 Knowledge per veggie level)": "最高解锁蔬菜的成本（每等级蔬菜2500美元+ 200知识）",
    "Cost:": "成本:",
    "Costs Knowledge, not money": "花费知识，而不是金钱",
    "Crucial for scaling income without manual management": "对于在没有人工管理的情况下扩大收入至关重要",
    "Cucumbers:": "黄瓜:",
    "Currency Check:": "货币检查:",
    "Currency Limits:": "货币上限：",
    "Currency:": "货币:",
    "Current knowledge multiplies gained experience per harvest by 1%": "当前的知识使每次收获的经验增加1%",
    "Current Knowledge:": "当前的知识:",
    "Current Progress:": "当前进度：",
    "Default sorting helps maximize income per time invested": "默认排序有助于最大化每次投资的收益",
    "Don't spend knowledge right away, as it boosts experience gain": "不要马上消耗知识，因为它可以增加经验",
    "Drought Chances:": "干旱几率：",
    "Drought:": "干旱:",
    "Each Better Seeds level gives 1.5× price instead of 1.25×": "每个“更好的种子”关卡提供1.5倍的价格，而不是1.25倍",
    "Each level adds +1 plot for that vegetable": "每一关增加1块蔬菜地",
    "Each plot harvests +1 additional vegetable": "每亩收获+1额外蔬菜",
    "Each recipe needs specific vegetables in specific quantities": "每种配方都需要一定量的特定蔬菜",
    "Each unlocked vegetable AND each additional plot counts toward your plot limit": "每个解锁的蔬菜和每个额外的地块都将计入您的地块限制",
    "Each vegetable can have multiple plots. More plots = more simultaneous growing!": "每一种蔬菜都可以有多个地块。更多的地块=更多的同步增长！",
    "Each vegetable has independent auto-purchasers": "每种蔬菜都有独立的自动购买者",
    "Each vegetable has its own individual upgrades that only affect that specific crop:": "每种蔬菜都有自己的单独升级，只影响特定的作物：",
    "Early Game:": "游戏早期：",
    "Earn knowledge points based on recipe complexity": "根据配方复杂度赚取知识点数",
    "Effect:": "效果:",
    "Essential for consistent growth rates": "对于持续的增长率至关重要",
    "Essential for idle gameplay and knowledge generation": "对于空闲的游戏玩法和知识生成至关重要",
    "Essential for idle gameplay progression": "对于空闲的游戏进程至关重要",
    "Essential for idle progression on fertilizer": "对肥料的闲置进度至关重要",
    "Essential upgrade! Eliminates Winter and Snow penalties": "必要的升级!消除冬季和雪的惩罚",
    "Example:": "例子:",
    "Expand your farm when you reach the maximum plots to increase your limit": "扩大你的农场，当你达到最大的地块，以增加你的限制",
    "Expansion Phase:": "扩张阶段:",
    "Experience determines how many plots your new farm has so stockpile it before prestige": "经验决定了你的新农场有多少块土地，所以在声望之前储存它",
    "Experience is earned every time you harvest any vegetable. Each vegetable requires a certain amount of experience to unlock:": "经验值是在每次收获蔬菜时获得的。每种蔬菜都需要一定的经验才能解锁：",
    "Experience Rewards:": "经验奖励:",
    "Experience Scaling:": "经验比例:",
    "Experience:": "经验:",
    "Fall:": "秋天：",
    "Family Recipe:": "家庭配方:",
    "Farm & Experience": "农场与经验值",
    "Farm Purchase Requirements:": "农场购买要求：",
    "Farm Tier Bonus:": "农场层奖励：",
    "Farm Tier:": "农场等级:",
    "Farm Upgrades": "农场升级",
    "Farmer's Almanac:": "农民历:",
    "Fertilizer Priority:": "肥料优先级:",
    "Fertilizer, Harvesters, Speed, Better Seeds reset to 0": "肥料，收割机，速度，良种重置为0",
    "Filter by availability, complexity, or type": "根据可用性、复杂性或类型进行筛选",
    "First farm costs $500, second costs $925, etc.": "第一个农场花费500美元，第二个农场花费925美元，等等。",
    "Focus on One Veggie:": "只吃一种蔬菜：",
    "Focus Strategy:": "集中策略:",
    "Formula:": "公式:",
    "Formula: 50 × 1.8^(index) for each vegetable": "公式：每种蔬菜50 × 1.8^(指数",
    "Function:": "功能:",
    "Gain both money and canning experience from completed recipes": "从完成的配方中获得金钱和罐头制作经验",
    "Game Help": "游戏帮助",
    "Get Surveyor to automatically increase production": "让测量员自动增加产量",
    "Global Upgrades:": "全局升级：",
    "Gray Button:": "灰色按钮：",
    "Green Beans, Zucchini, Cucumbers, Tomatoes, Peppers": "采购产品青豆，西葫芦，黄瓜，西红柿，辣椒",
    "Green Beans:": "绿豆:",
    "Green Button:": "绿色按钮:",
    "Greenhouse, Irrigation, Almanac, Auto-Sell, Heirloom reset": "温室，灌溉，年鉴，自动出售，传家宝复位",
    "Greenhouse:": "温室:",
    "Harvester First:": "收获:",
    "Harvesting:": "收获:",
    "Heatwave Chances:": "热浪发生的机会：",
    "Heatwave:": "热浪:",
    "Heirloom Seeds:": "传家宝种子:",
    "Heirloom Touch:": "传家宝联系:",
    "How it Works:": "工作原理：",
    "If multiple auto-purchasers need the same currency, earlier vegetables get priority": "如果多个汽车购买者需要相同的货币，那么较早的蔬菜将获得优先权",
    "Improves Better Seeds upgrade from 1.25× to 1.5× per level": "每级提升优质种子1.25倍至1.5倍",
    "Increases sale price (1.25x per level, 1.5x with Heirloom Seeds)": "增加销售价格（每级1.25倍，传家宝种子1.5倍）",
    "Increases sale price by 1.25× per level (1.5× with Heirloom Seeds)": "每升一级增加1.25倍的销售价格（使用传家宝种子增加1.5倍）",
    "Increases sale price of canned goods": "提高罐装食品的销售价格",
    "Increases vegetables per harvest for exponential growth": "增加每收获蔬菜指数增长",
    "Ingredient Checking:": "配料检查：",
    "Irrigation:": "灌溉:",
    "Keep a good stock of common vegetables for consistent canning": "保持一个良好的库存的常见蔬菜一致罐装",
    "Knowledge × (1 + almanac level × 0.10)": "知识水平×（1 +年历水平× 0.10）",
    "Knowledge Earning:": "知识获得:",
    "Knowledge factors into experience gain, so don't spend all of it at once.": "知识是积累经验的重要因素，所以不要一下子把所有的知识都花光。",
    "Knowledge is a secondary currency earned from harvesting vegetables:": "知识是通过收获蔬菜获得的第二货币；",
    "Knowledge Management:": "知识管理:",
    "Knowledge per plot (scales with max plots)": "每个地块的知识（以最大地块为尺度）",
    "Knowledge Phase:": "知识阶段:",
    "Knowledge Planning:": "知识规划:",
    "Knowledge Rewards:": "知识奖励:",
    "Knowledge Uses:": "知识用途：",
    "Late Game:": "游戏后期:",
    "Leftover money after paying farm cost": "支付农场成本后剩下的钱",
    "Lettuce:": "生菜:",
    "Level 10 = +50% growth (1.5× speed)": "10级= +50%的成长（1.5倍速度）",
    "Level 10 = 33 seconds between harvests": "10级=收获间隔33秒",
    "Level 3 Better Seeds = 1.95× sale price (2.92× with Heirloom)": "三级优质种子= 1.95×销售价格（带有传家宝= 2.92×）",
    "Level 5 Almanac = +50% knowledge from all sources": "5级年鉴= +50%的知识来源",
    "Level Scaling:": "等级缩放：",
    "Manage Ingredients:": "管理材料:",
    "Manual Control:": "手动控制:",
    "Manual Harvest:": "手工收获:",
    "Massive late-game money multiplier": "巨大的游戏后期资金乘数",
    "Max Levels:": "最大等级：",
    "Max Plots:": "最大地块：",
    "Money:": "金钱:",
    "Most cost-effective upgrade for increasing income": "最具成本效益的升级，以增加收入",
    "Multiple Processes:": "多个进程:",
    "Multiplies ALL knowledge gains by (1 + level)": "所有获得的知识乘以（1 + 1级）",
    "Must have used ALL available plots": "必须使用所有可用的地块",
    "No bonuses": "没有奖金",
    "No levels, just owned/not owned": "没有级别，只有拥有/不拥有",
    "No need to manually click Sell All": "无需手动单击“全部出售”",
    "Normal growth (no bonus/penalty)": "正常成长（无奖励/惩罚）",
    "Normal growth rates": "正常增长率",
    "Not purchased and can't afford": "没买也买不起",
    "Not purchased but affordable - click to buy!": "没有购买，但负担得起-点击购买！",
    "Note:": "注意:",
    "One-Time Purchase:": "一次性购买:",
    "Onions:": "洋葱:",
    "Only starts recipes you can actually make": "只开始你真正能做的配方",
    "Only useful after buying the Auto Harvester": "只有在购买自动矿车后才有用",
    "Peppers:": "辣椒:",
    "Per-Vegetable Setup:": "每个蔬菜设置：",
    "Per-Vegetable Upgrades": "每种蔬菜的升级",
    "Per-Vegetable:": "每种蔬菜：",
    "Permanent progression level": "永久等级",
    "Picks the first available recipe in your selected sort order": "按所选排序顺序选择第一个可用配方",
    "Plot Limit:": "地块限制：",
    "Plot Limitations:": "地块限制:",
    "Plots vs New Vegetables:": "地块vs新蔬菜：",
    "Prestige Timing:": "声望时间:",
    "Prevents -100% growth penalty during Snow": "大雪状态下，不会受到-100%的成长惩罚",
    "Prevents -50% growth penalty during Drought": "在干旱期间防止-50%的生长损失",
    "Prevents -90% growth penalty in Winter": "防止冬季-90%的生长惩罚",
    "Previous max + (experience ÷ 100) new plots (capped at 2x current max)": "以前的最大值+（经验÷ 100）新地块（上限为当前最大值的2倍）",
    "Progression:": "进度：",
    "Protects against Drought events": "防止干旱事件",
    "Purchase Check:": "购买检查：",
    "Purchase only happens if you have enough money or knowledge": "只有当你有足够的钱或知识时，才会购买",
    "Purchased and currently ON": "已购买，当前处于开启状态",
    "Purchased but currently OFF": "已购买但目前关闭",
    "Purchases:": "购买:",
    "Quick Hands:": "快手：",
    "Radish → Lettuce → Green Beans → Zucchini → Cucumbers → Tomatoes → Peppers → Carrots → Broccoli → Onions": "萝卜→莴苣→青豆→西葫芦→黄瓜→西红柿→辣椒→胡萝卜→西兰花→洋葱",
    "Radish, Lettuce, Carrots, Broccoli, Cabbage": "萝卜，莴苣，胡萝卜，花椰菜，卷心菜",
    "Radish, Lettuce, Carrots, Cabbage, Onions": "萝卜，莴苣，胡萝卜，卷心菜，洋葱",
    "Radish:": "萝卜:",
    "Rain Chances:": "下雨机会：",
    "Rain:": "雨:",
    "Reach 5,000 experience to access canning": "达到5000经验进入罐头",
    "Recipe Details:": "配方细节:",
    "Recipe Filtering:": "配方筛选:",
    "Recipe Requirements:": "配方要求:",
    "Recipe Selection:": "配方选择:",
    "Recipe Sorting:": "配方分类:",
    "Recipes take time to complete (varies by complexity)": "配方需要时间来完成（因复杂程度而异）",
    "Red Button:": "红色按钮:",
    "Reduced Rewards:": "减少奖励:",
    "Reduces processing time for faster production": "减少加工时间，提高生产速度",
    "Remember to activate auto-purchasers on each new vegetable you unlock": "记得在你解锁的每一种新蔬菜上激活自动购买者",
    "Resets when you buy a larger farm (prestige)": "当你购买更大的农场时重置（声望）",
    "Run several recipes simultaneously (upgrade to increase slots)": "同时运行多个配方（升级以增加插槽）",
    "Save knowledge for the experience boost rather than immediate upgrades": "为经验提升节省知识，而不是立即升级",
    "Season Effects:": "季节效应:",
    "Seasonal Bonuses:": "季节性的奖金:",
    "Seasonal Vegetable Bonuses (+10% growth):": "季节性蔬菜奖励（+10%增长）：",
    "Seasons": "季节",
    "Seasons & Weather": "季节和天气",
    "Show ingredients, profit, processing time, and reward amounts": "显示配料、利润、加工时间和奖励金额",
    "Small Cards:": "小卡牌：",
    "Snow Protection:": "雪保护:",
    "Snow:": "雪:",
    "Solution:": "解决方案:",
    "Sort by name, profit, time, or difficulty": "按名称、利润、时间或难度排序",
    "Sort by Profit:": "按利润排序：",
    "Spring → Summer → Fall → Winter": "春天→夏天→秋天→冬天",
    "Spring:": "春天:",
    "Spring: 1.2% • Summer: 1.2% • Fall: 1.6% • Winter: 0.4%": "春季：1.2%•夏季：1.2%•秋季：1.6%•冬季：0.4%",
    "Spring: 20% • Summer: 16% • Fall: 14% • Winter: 10%": "春季：20%•夏季：16%•秋季：14%•冬季：10%",
    "Spring: 4% • Summer: 6% • Fall: 3% • Winter: 1%": "春季：4%•夏季：6%•秋季：3%•冬季：1%",
    "Spring/Summer/Fall:": "春/夏/秋:",
    "Start Simple:": "简单的开始:",
    "Starting Plots:": "起始地块：",
    "Storm Chances:": "风暴几率：",
    "Storm:": "风暴:",
    "Strategy Tips:": "策略建议:",
    "Strategy:": "策略:",
    "Summer:": "夏天：",
    "The game cycles through four seasons:": "游戏周期分为四个季节：",
    "These upgrades affect your entire farm and apply to all vegetables:": "这些升级会影响你的整个农场，适用于所有蔬菜：",
    "Timer = 50 ÷ (1 + level × 0.05) ticks": "计时器= 50 ÷（1 +级别× 0.05）个刻度",
    "Timer restarts for another 7-day cycle": "计时器重新开始另一个7天的周期",
    "Timer:": "定时器:",
    "Timing:": "时间:",
    "Toggle Control:": "切换控制:",
    "Tomatoes:": "西红柿:",
    "Total plots across ALL vegetables cannot exceed farm limit": "所有蔬菜的种植面积不能超过农场限制",
    "Total plots cannot exceed your farm limit": "地块总数不能超过你的农场限制",
    "Transforms Winter from terrible to normal growing season": "把冬天从可怕的季节变成正常的生长季节",
    "Triggers once per day at day transition": "每天在白天转换时触发一次",
    "Turn off auto-purchasers if you need to save currency for big purchases": "如果你需要为大件购买节省资金，就关闭自动购买功能",
    "Unlock Requirement:": "解锁要求:",
    "Unlocks advanced recipes with better rewards": "解锁具有更好奖励的高级配方",
    "Upgrade Progressively:": "逐步升级:",
    "Upgrade simultaneous processes to handle multiple recipes": "升级同步进程以处理多个配方",
    "Upgrades Additional Plot automatically": "自动升级附加地块",
    "Upgrades Better Seeds automatically": "自动升级更好的种子",
    "Upgrades Fertilizer automatically": "自动升级肥料",
    "Upgrades Harvester Speed automatically": "自动升级矿车速度",
    "Use manual canning for high-value recipes, auto for idle play": "高价值的配方使用手动罐装，空闲时使用自动罐装",
    "Uses Money ($)": "使用货币（$）",
    "Usually better to max one vegetable than spread upgrades around": "通常最好是把一种蔬菜加满，而不是到处升级",
    "Value:": "价值：",
    "Vegetable Order:": "蔬菜:",
    "Vegetable Unlock Requirements:": "蔬菜解锁要求：",
    "Veggie Upgrades": "素食升级",
    "Weather changes randomly each day with different probabilities by season:": "天气每天随机变化，随季节变化的概率不同：",
    "Weather Effects:": "天气的影响:",
    "Weather Probabilities by Season:": "按季节划分的天气概率：",
    "Weather Protection:": "天气保护:",
    "What Resets:": "重置:",
    "What You Keep:": "你保留的东西：",
    "When timer reaches 0, each active auto-purchaser attempts to buy its upgrade": "当计时器达到0时，每个活跃的自动购买者尝试购买其升级",
    "When you've used all available plots, you can buy a larger farm to reset progress but gain permanent bonuses:": "当你用完所有可用的地块后，你可以购买一个更大的农场来重置进度，但会获得永久奖励：",
    "Winter Protection:": "冬天保护:",
    "Yellow Glow:": "黄色发光:",
    "You can toggle each auto-purchaser ON/OFF at any time after purchase": "您可以在购买后的任何时间切换每个自动购买开关",
    "Zucchini:": "西葫芦:",
    "Automatically starting recipes": "自动开始配方",
    "Canned Zucchini": "南瓜罐头",
    "Click to enable automation": "点击开启自动化",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Kn": "知识",
    "kn": "知识",
    "s)": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "(~": "(~",
    "($": "($",
    "/": "/",
    "%": "%",
    "$": "$",
    "%)": "%)",
    "✓": "✓",
    "×": "×",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "Growth rate: ": "成长速率：",
    "Sale price: ": "销售价格：",
    "Extra veggies per harvest: ": "每次收获额外蔬菜：",
    "Harvest time: ": "收获时间: ",
    "Knowledge gain: ": "知识增益: ",
    "Bonus chance: ": "加成几率: ",
    "Max processes: ": "最大进程: ",
    "Processing time: ": "处理时间: ",
    "Found Archie! +": "发现阿奇! +",
    "Missing: ": "缺少: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "% growth rate, drought immunity": "% 生长速率，抗旱能力",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^\+([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^\$([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)K Kn$/, '([\d\.]+)K 知识'],
    [/^(.+) \& (.+) Kn$/, '$1 & $2 知识'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) exp$/, '$1 经验值'],
    [/^([\d\.,]+) Kn$/, '$1 Kn'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^Exp: ([\d\.,]+)$/, '经验值: $1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);